export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const ACTIVATE_USER = "ACTIVATE_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_CONFIRM = "RESET_PASSWORD_CONFIRM";
