export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_ONE_MOVIE = "FETCH_ONE_MOVIE";
export const SET_MOVIES = "SET_MOVIES";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
export const TOGGLE_FAVOURITE_MOVIE = "TOGGLE_FAVOURITE_MOVIE";
