export enum COUNTRIES {
    AUSTRALIA = "Австралия",
    ARGENTINA = "Аргентина",
    BRITAIN = "Великобритания",
    GERMANY = "Германия",
    HONG_KONG = "Гонконг",
    SPAIN = "Испания",
    ITALY = "Италия",
    KAZARHSTAN = "Казахстан",
    CANADA = "Канада",
    CHINA = "Китай",
    NETHERLANDS = "Нидерланды",
    NORWAY = "Норвегия",
    RUSSIA = "Россия",
    USA = "США",
    SERBIA = "Сербия",
    TURKEY = "Турция",
    UKRAINE = "Украина",
    FRANCE = "Франция",
    SWITZERLAND = "Швейцария",
    SWEDEN = "Швеция",
    JAPAN = "Япония",
}
