export type { IMovie } from "./movie";
export type { ICountry } from "./country";
export type { IFees } from "./fees";
export type { IGenre } from "./genre";
export type { IPerson } from "./person";
export type { IPoster } from "./poster";
export type { IPremiere } from "./premier";
export type { IRating } from "./rating";
export type { IUser } from "./user";
