import { ICountry } from "./country";
import { IFees } from "./fees";
import { IGenre } from "./genre";
import { IPerson } from "./person";
import { IPoster } from "./poster";
import { IPremiere } from "./premier";
import { IRating } from "./rating";

export interface IMovie {
    id: number;
    name?: string;
    alternativeName: string | null;
    enName?: unknown;
    type: string;
    typeNumber: number;
    year: number | null;
    description: string | null;
    shortDescription?: string | null;
    slogan?: unknown;
    status?: unknown;
    rating: IRating;
    votes: IRating;
    movieLength: number | null;
    totalSeriesLength?: unknown;
    seriesLength?: unknown;
    ratingMpaa: string | null;
    ageRating?: unknown;
    poster?: IPoster;
    genres: IGenre[];
    countries: ICountry[];
    persons: IPerson[];
    fees?: IFees;
    premiere?: IPremiere;
    top10?: unknown;
    top250?: unknown;
    isSeries: boolean;
    ticketsOnSale: boolean;
    lists: unknown[];
    createdAt: string;
    updatedAt: string;
}
